runtime: python311
entrypoint: gunicorn -b :$PORT app:server

automatic_scaling:
  max_instances: 2

handlers:
- url: /assets
  static_dir: assets

- url: /figures
  static_dir: figures

- url: /.*
  script: auto